apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: datastore
  labels:
    name: mysql-svc
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: datastore
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
      app: mysql
  template:
    metadata:
      labels:
        name: mysql
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "sleep 10; mysql --host=127.0.0.1 --user=root --password=$MYSQL_ROOT_PASSWORD --execute 'CREATE DATABASE IF NOT EXISTS php_k8s_db'"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "false"
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_USER
            value: developer
          - name: MYSQL_PASSWORD
            value: supersecret
        volumeMounts:
          - name: data-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: data-storage
          hostPath:
            path: /data/mysql
            type: DirectoryOrCreate
