apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: datastore
  labels:
    name: redis-svc
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: datastore
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app: redis
  template:
    metadata:
      labels:
        name: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2
        ports:
        - containerPort: 6379
